project_id = "llioeafzlhrjqwkjaepe"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.send-trial-reminders]
    verify_jwt = true
  [functions.qa-test-admin]
    verify_jwt = false
